import streamlit as st
import requests

# Function to generate response using Bard API
def generate_response(prompt):
  url = "https://bard.google.com/generate"
  headers = {"Authorization": st.secrets["Bard-API"]}
  payload = {"model": "bard-1.5-base", "prompt": prompt}
  response = requests.post(url, headers=headers, json=payload)
  return response.json()["text"].strip()

# Streamlit app interface
st.title("Text-Based Q&A with Bard")
st.write("Enter your question and get a response generated by Bard.")

# Text input for user query
user_query = st.text_input("Your Question:")

# Button to trigger response generation
if st.button("Ask Bard"):
  if user_query:
    with st.spinner("Generating Response..."):  # Display spinner while generating response
      response = generate_response(user_query)
    st.write("Bard's Response:")
    st.write(response)
  else:
    st.error("Please enter your question.")

